export const EXPORT_LIST_REQUEST = 'EXPORT_LIST_REQUEST';
export const EXPORT_LIST_SUCCESS = 'EXPORT_LIST_SUCCESS';
export const EXPORT_LIST_FAIL = 'EXPORT_LIST_FAIL';

export const EXPORT_DETAILS_REQUEST = 'EXPORT_DETAILS_REQUEST';
export const EXPORT_DETAILS_SUCCESS = 'EXPORT_DETAILS_SUCCESS';
export const EXPORT_DETAILS_FAIL = 'EXPORT_DETAILS_FAIL';
export const EXPORT_DETAILS_RESET = 'EXPORT_DETAILS_RESET';


export const EXPORT_CREATE_REQUEST = 'EXPORT_CREATE_REQUEST';
export const EXPORT_CREATE_SUCCESS = 'EXPORT_CREATE_SUCCESS';
export const EXPORT_CREATE_FAIL = 'EXPORT_CREATE_FAIL';
export const EXPORT_CREATE_RESET = 'EXPORT_CREATE_RESET';

export const EXPORT_UPDATE_REQUEST = 'EXPORT_UPDATE_REQUEST';
export const EXPORT_UPDATE_SUCCESS = 'EXPORT_UPDATE_SUCCESS';
export const EXPORT_UPDATE_FAIL = 'EXPORT_UPDATE_FAIL';
export const EXPORT_UPDATE_RESET = 'EXPORT_UPDATE_RESET';

export const EXPORT_DELETE_REQUEST = 'EXPORT_DELETE_REQUEST';
export const EXPORT_DELETE_SUCCESS = 'EXPORT_DELETE_SUCCESS';
export const EXPORT_DELETE_FAIL = 'EXPORT_DELETE_FAIL';
export const EXPORT_DELETE_RESET = 'EXPORT_DELETE_RESET';