export const IMPORT_LIST_REQUEST = 'IMPORT_LIST_REQUEST';
export const IMPORT_LIST_SUCCESS = 'IMPORT_LIST_SUCCESS';
export const IMPORT_LIST_FAIL = 'IMPORT_LIST_FAIL';

export const IMPORT_DETAILS_REQUEST = 'IMPORT_DETAILS_REQUEST';
export const IMPORT_DETAILS_SUCCESS = 'IMPORT_DETAILS_SUCCESS';
export const IMPORT_DETAILS_FAIL = 'IMPORT_DETAILS_FAIL';
export const IMPORT_DETAILS_RESET = 'IMPORT_DETAILS_RESET';


export const IMPORT_CREATE_REQUEST = 'IMPORT_CREATE_REQUEST';
export const IMPORT_CREATE_SUCCESS = 'IMPORT_CREATE_SUCCESS';
export const IMPORT_CREATE_FAIL = 'IMPORT_CREATE_FAIL';
export const IMPORT_CREATE_RESET = 'IMPORT_CREATE_RESET';

export const IMPORT_UPDATE_REQUEST = 'IMPORT_UPDATE_REQUEST';
export const IMPORT_UPDATE_SUCCESS = 'IMPORT_UPDATE_SUCCESS';
export const IMPORT_UPDATE_FAIL = 'IMPORT_UPDATE_FAIL';
export const IMPORT_UPDATE_RESET = 'IMPORT_UPDATE_RESET';

export const IMPORT_DELETE_REQUEST = 'IMPORT_DELETE_REQUEST';
export const IMPORT_DELETE_SUCCESS = 'IMPORT_DELETE_SUCCESS';
export const IMPORT_DELETE_FAIL = 'IMPORT_DELETE_FAIL';
export const IMPORT_DELETE_RESET = 'IMPORT_DELETE_RESET';