export const SHELF_LIST_REQUEST = 'SHELF_LIST_REQUEST';
export const SHELF_LIST_SUCCESS = 'SHELF_LIST_SUCCESS';
export const SHELF_LIST_FAIL = 'SHELF_LIST_FAIL';

export const SHELF_DETAILS_REQUEST = 'SHELF_DETAILS_REQUEST';
export const SHELF_DETAILS_SUCCESS = 'SHELF_DETAILS_SUCCESS';
export const SHELF_DETAILS_FAIL = 'SHELF_DETAILS_FAIL';
export const SHELF_DETAILS_RESET = 'SHELF_DETAILS_RESET';


export const SHELF_CREATE_REQUEST = 'SHELF_CREATE_REQUEST';
export const SHELF_CREATE_SUCCESS = 'SHELF_CREATE_SUCCESS';
export const SHELF_CREATE_FAIL = 'SHELF_CREATE_FAIL';
export const SHELF_CREATE_RESET = 'SHELF_CREATE_RESET';

export const SHELF_UPDATE_REQUEST = 'SHELF_UPDATE_REQUEST';
export const SHELF_UPDATE_SUCCESS = 'SHELF_UPDATE_SUCCESS';
export const SHELF_UPDATE_FAIL = 'SHELF_UPDATE_FAIL';
export const SHELF_UPDATE_RESET = 'SHELF_UPDATE_RESET';

export const SHELF_DELETE_REQUEST = 'SHELF_DELETE_REQUEST';
export const SHELF_DELETE_SUCCESS = 'SHELF_DELETE_SUCCESS';
export const SHELF_DELETE_FAIL = 'SHELF_DELETE_FAIL';
export const SHELF_DELETE_RESET = 'SHELF_DELETE_RESET';